spring:
  application:
    name: sdapi
  datasource:
    url: jdbc:h2:mem:db
    username: user
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080