spring:
  application:
    name: sdapi
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: filesystem:./migration

jwt:
  secret: secret
  expiration: 3600000

server:
  port: 8080